import {
  RestartClusterCont,
  StartClusterCont,
  StopClusterCont,
  RestartMessangerCont,
  StopMessangerCont,
  StartMessangerCont,
  RestartSshclientCont,
  StopSshclientCont,
  StartSshclientCont,
  RestartScheduleCont,
  StopScheduleCont,
  StartScheduleCont,
  RestartProxyCont,
  StopProxyCont,
  StartProxyCont,
  RestartServerCont,
  StopServerCont,
  StartServerCont,
  RestartWebCont,
  StopWebCont,
  StartWebCont,
  RestartEsp32Cont,
  StopEsp32Cont,
  StartEsp32Cont,
  RestartPostgresCont,
  StopPostgresCont,
  StartPostgresCont,
  getClusterLogging,
  getMessangerLogging,
  getSshclientLogging,
  getScheduleLogging,
  getProxyLogging,
  getServerLogging,
  getWebLogging,
  getEsp32Logging,
  ClearClusterLogging,
  ClearMessangerLogging,
  ClearSshclientLogging,
  ClearScheduleLogging,
  ClearProxyLogging,
  ClearServerLogging,
  ClearWebLogging,
  ClearEsp32Logging,
} from '../api/backupApi';
import { computed } from 'vue';

export function createServices(state) {
  return computed(() => [
    {
      title: 'Cluster',
      disable: !state.value.ClusterService,
      logging: getClusterLogging,
      clear: ClearClusterLogging,
      restart: RestartClusterCont,
      start: StartClusterCont,
      stop: StopClusterCont,
    },
    {
      title: 'Proxy',
      disable: !state.value.ProxyService,
      logging: getProxyLogging,
      clear: ClearProxyLogging,
      restart: RestartProxyCont,
      start: StartProxyCont,
      stop: StopProxyCont,
    },
    {
      title: 'Server',
      disable: !state.value.ServerService,
      logging: getServerLogging,
      clear: ClearServerLogging,
      restart: RestartServerCont,
      start: StartServerCont,
      stop: StopServerCont,
    },
    {
      title: 'Web',
      disable: !state.value.WebService,
      logging: getWebLogging,
      clear: ClearWebLogging,
      restart: RestartWebCont,
      start: StartWebCont,
      stop: StopWebCont,
    },
    {
      title: 'Esp32',
      disable: !state.value.Esp32Service,
      logging: getEsp32Logging,
      clear: ClearEsp32Logging,
      restart: RestartEsp32Cont,
      start: StartEsp32Cont,
      stop: StopEsp32Cont,
    },
    {
      title: 'Sshclient',
      disable: !state.value.SshclientService,
      logging: getSshclientLogging,
      clear: ClearSshclientLogging,
      restart: RestartSshclientCont,
      start: StartSshclientCont,
      stop: StopSshclientCont,
    },
    {
      title: 'Schedule',
      disable: !state.value.ScheduleService,
      logging: getScheduleLogging,
      clear: ClearScheduleLogging,
      restart: RestartScheduleCont,
      start: StartScheduleCont,
      stop: StopScheduleCont,
    },
    {
      title: 'Messanger',
      disable: !state.value.MessangerService,
      logging: getMessangerLogging,
      clear: ClearMessangerLogging,
      restart: RestartMessangerCont,
      start: StartMessangerCont,
      stop: StopMessangerCont,
    },
    {
      title: 'Postgres',
      disable: !state.value.PostgresService,
      restart: RestartPostgresCont,
      start: StartPostgresCont,
      stop: StopPostgresCont,
    },
  ]);
}

export default {};
