import {
  RestartClusterCont,
  StartClusterCont,
  StopClusterCont,
  RestartMessangerCont,
  StopMessangerCont,
  StartMessangerCont,
  RestartSshclientCont,
  StopSshclientCont,
  StartSshclientCont,
  RestartScheduleCont,
  StopScheduleCont,
  StartScheduleCont,
  RestartProxyCont,
  StopProxyCont,
  StartProxyCont,
  RestartServerCont,
  StopServerCont,
  StartServerCont,
  RestartWebCont,
  StopWebCont,
  StartWebCont,
  RestartEsp32Cont,
  StopEsp32Cont,
  StartEsp32Cont,
  RestartGogsCont,
  StopGogsCont,
  StartGogsCont,
  RestartPostgresCont,
  StopPostgresCont,
  StartPostgresCont,
} from '../api/mainApi';

export function createServices(state) {
  return [
    {
      title: 'Cluster',
      disable: !!state.value.ClusterService,
      restart: RestartClusterCont,
      start: StartClusterCont,
      stop: StopClusterCont,
    },
    {
      title: 'Messanger',
      disable: !!state.value.MessangerService,
      restart: RestartMessangerCont,
      start: StartMessangerCont,
      stop: StopMessangerCont,
    },
    {
      title: 'Sshclient',
      disable: !!state.value.SshclientService,
      restart: RestartSshclientCont,
      start: StartSshclientCont,
      stop: StopSshclientCont,
    },
    {
      title: 'Schedule',
      disable: !!state.value.ScheduleService,
      restart: RestartScheduleCont,
      start: StartScheduleCont,
      stop: StopScheduleCont,
    },
    {
      title: 'Proxy',
      disable: !!state.value.ProxyService,
      restart: RestartProxyCont,
      start: StartProxyCont,
      stop: StopProxyCont,
    },
    {
      title: 'Server',
      disable: !!state.value.ServerService,
      restart: RestartServerCont,
      start: StartServerCont,
      stop: StopServerCont,
    },
    {
      title: 'Web',
      disable: !!state.value.WebService,
      restart: RestartWebCont,
      start: StartWebCont,
      stop: StopWebCont,
    },
    {
      title: 'Esp32',
      disable: !!state.value.Esp32,
      restart: RestartEsp32Cont,
      start: StartEsp32Cont,
      stop: StopEsp32Cont,
    },
    {
      title: 'Gogs',
      disable: !!state.value.GogsService,
      restart: RestartGogsCont,
      start: StartGogsCont,
      stop: StopGogsCont,
    },
    {
      title: 'Postgres',
      disable: !!state.value.PostgresService,
      restart: RestartPostgresCont,
      start: StartPostgresCont,
      stop: StopPostgresCont,
    },
  ];
}

export default {};
